require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 15

RSpec/DescribedClass:
  EnforcedStyle: explicit

Rails/HasManyOrHasOneDependent:
  Enabled: false
